# pacman configuration for the Antenora live image build
[options]
Architecture = auto
CheckSpace
Color
SigLevel = Required DatabaseOptional
ParallelDownloads = 5

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
